### ISSUE TITLE
Add 2024-2025 Team Section

### ISSUE THREAD

**Issue by Shaar03** [GDSC-YU/website#17]
We need to update the website to include the new team members and events for the 2024-2025 academic year.

Tasks:
- [x] Team members: Add the names, roles, and social links of the team members for the 2024-2025 year.
- [x] Events: Add a section to add events planned for this academic year.

Additional Notes:
- [x] Ensure that the formatting and design are consistent with previous sections.

**Comment by S-S-Poojitha** [comment]
I see that this issue has been assigned to Lily-270. If they’re open to collaboration, I’d love to assist with it. 
Would it be possible for me to contribute or provide support in resolving this issue?
